language: php

php: [5.6, 7.0, 7.1]

sudo: false

allow_failures:
  - php: 7.0
  - php: 7.1

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - travis_retry composer install --prefer-dist --no-interaction --dev

script:
  - composer ci
